@base_url=http://localhost:8081/api/v1
@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJtaWhhaUBnbWFpbC5jb20iLCJleHAiOjE2MzE3MjU3NDAsImlzcyI6Imdvb2dsZS5jb20ifQ.BtJiKLJZgxP0R3rG7IYFWesAUfdb-l6ujvgygVGlgio

@refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mzg5ODMxNjAsImlzcyI6Imdvb2dsZS5jb20ifQ.Qt2hmUdsD5NCV5Gyljsok4MyDnXoPtzow-88y5_tFxw

@confirm_token=0P7KU0mzNn

@api_key=aKrq3FC6wuOcRmCLV1EV

###

GET {{base_url}}/health-check HTTP/2.0
content-type: application/json

###

POST {{base_url}}/user/login HTTP/2.0
content-type: application/json
Authorization: Bearer {{api_key}}

{
	"email": "mihai@gmail.com",
	"password": "intrex"
}

###

POST {{base_url}}/user/register HTTP/2.0
content-type: application/json
Authorization: Bearer {{api_key}}

{
	"first_name": "Mihai",
	"last_name": "Blebea",
    "email": "mihai@gmail.com",
	"password": "intrex",
	"confirm_success_url": "https://www.google.com",
	"confirm_fail_url": "https://www.fengshuiarmoie.ro"
}

###

POST {{base_url}}/user/authorize HTTP/2.0
content-type: application/json
Authorization: Bearer {{api_key}}

{
	"access_token": "{{access_token}}"
}

###


POST {{base_url}}/user/refresh HTTP/2.0
content-type: application/json
Authorization: Bearer {{api_key}}

{
	"refresh_token": "{{refresh_token}}"
}

###

POST {{base_url}}/user/confirm HTTP/2.0
content-type: application/json
Authorization: Bearer {{api_key}}

{
	"confirm_token": "{{confirm_token}}"
}

###

POST {{base_url}}/project HTTP/2.0
content-type: application/json

{
	"name": "NiceProject",
	"host": "nice-project.com"
}
