@base_url=http://localhost:8081/api/v1
@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJtaWhhaUBnbWFpbC5jb20iLCJleHAiOjE2MzE3MDA1NjAsImlzcyI6Imdvb2dsZS5jb20ifQ.hXy_TRLDCFUuzH5is9vEAu1s6E-JZiS1g882CP_Q-Ic

@refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mzg5NTczMTIsImlzcyI6Imdvb2dsZS5jb20ifQ.fW2YiYPJcQOaZ8uvTqpV1mRv50mgCM7VUdroBT-t1gc

@confirm_token=BpLnfgDsc2

###

GET {{base_url}}/health-check HTTP/2.0
content-type: application/json

###

POST {{base_url}}/login HTTP/2.0
content-type: application/json

{
	"email": "mihai@gmail.com",
	"password": "intrex"
}

###

POST {{base_url}}/register HTTP/2.0
content-type: application/json

{
	"first_name": "Mihai",
	"last_name": "Blebea",
    "email": "mihai@gmail.com",
	"password": "intrex"
}

###

POST {{base_url}}/authorize HTTP/2.0
content-type: application/json

{
	"access_token": "{{access_token}}"
}

###


POST {{base_url}}/refresh HTTP/2.0
content-type: application/json

{
	"refresh_token": "{{refresh_token}}"
}

###

POST {{base_url}}/confirm HTTP/2.0
content-type: application/json

{
	"confirm_token": "{{confirm_token}}"
}
